name: exchange_rates
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  hydrated_bloc: ^8.0.0
  dio: ^4.0.4
  path_provider: ^2.0.8
  flutter_reorderable_list: ^1.2.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  test: ^1.17.10
flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
